### ISSUE TITLE
Several bugs in the latest version.

### ISSUE THREAD

**Issue by lyuwen** [atztogo/phono3py#25]
I installed the latest version of the package using [conda](https://atztogo.github.io/phono3py/install.html#installation-using-conda) (i.e. `conda install -c atztogo phono3py`), and got the following:
```
Traceback (most recent call last):
  File "$HOME/miniconda2/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.17.0.post1', 'phono3py')
  File "$HOME/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "$HOME/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "$HOME/miniconda2/lib/python2.7/site-packages/phono3py-1.17.0.post1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 43, in <module>

ImportError: cannot import name get_force_sets
```
I modified the `scripts/phono3py` file and run the thermal conductivity calculation, and it ended up with this error
```
Traceback (most recent call last):
  File "$HOME/miniconda2/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.17.0.post1', 'phono3py')
  File "$HOME/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "$HOME/miniconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1469, in run_script
    exec(script_code, namespace, namespace)
  File "$HOME/miniconda2/lib/python2.7/site-packages/phono3py-1.17.0.post1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 960, in <module>

  File "$HOME/miniconda2/lib/python2.7/site-packages/phono3py-1.17.0.post1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 84, in finalize_phono3py

  File "build/bdist.linux-x86_64/egg/phono3py/cui/phono3py_yaml.py", line 81, in set_phonon_info
  File "build/bdist.linux-x86_64/egg/phonopy/interface/phonopy_yaml.py", line 118, in set_phonon_info
AttributeError: 'Phono3py' object has no attribute 'force_constants'
```

Please check, thank you very much.

**Comment by atztogo** [comment]
Could you try the latest commits of phonopy develop branch and phono3py develop branch together?

**Comment by lyuwen** [comment]
I just used the develop branch of both repositories. And I'm on a fresh installation of ubuntu 18.04, I installed libopenblas-dev, libomp5-dev, liblapack-dev, liblapacke-dev, libgomp1, and I got this error
```
Traceback (most recent call last):
  File "$HOME/.local/bin/phono3py", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "$HOME/git_projects/phono3py/scripts/phono3py", line 875, in <module>
    solve_dynamical_matrices=(not settings.get_read_phonon()))
  File "$HOME/git_projects/phono3py/phono3py/api_phono3py.py", line 458, in set_phph_interaction
    verbose=self._log_level)
  File "$HOME/git_projects/phono3py/phono3py/phonon3/interaction.py", line 285, in set_dynamical_matrix
    self.set_phonons(verbose=verbose)
  File "$HOME/git_projects/phono3py/phono3py/phonon3/interaction.py", line 329, in set_phonons
    self._set_phonon_c(_grid_points, verbose=verbose)
  File "$HOME/git_projects/phono3py/phono3py/phonon3/interaction.py", line 391, in _set_phonon_c
    verbose=verbose)
  File "$HOME/git_projects/phono3py/phono3py/phonon/solver.py", line 15, in set_phonon_c
    import phono3py._phono3py as phono3c
ImportError: $HOME/git_projects/phono3py/phono3py/_phono3py.so: undefined symbol: LAPACKE_dsyev
```

**Comment by lyuwen** [comment]
I somehow solved this error and everything is now working in the develop branch. The previously reported bugs are cleared. Thank you very much.

**Comment by lyuwen** [comment]
In your `setup.py` code, you are checking for `/usr/lib/liblapacke.so` but you do not check `/usr/lib/x86_64-linux-gnu/liblapacke.so` or `/usr/lib/x86_64-linux-gnu/liblapacke.a`, which is the most common places one can find `liblapacke` in ubuntu systems, and in some other systems it might be in `/usr/lib64/liblapacke.so`. 
Is it intended for user to provide the location of the file? Would it be easier to execute command `locate liblapacke.so` to try to find it or give user an option from command line to pass in the location of the file?

**Comment by atztogo** [comment]
I think it is not a good idea to use `locate liblapacke.so` because multiple of those can be found. Users should provide their own setup.py configurations by themselves. Currently my best recommendation is using conda.
