### ISSUE TITLE
AttributeError: 'Phono3py' object has no attribute 'force_constants'

### ISSUE THREAD

**Issue by xiangpan2017** [atztogo/phono3py#26]
Dear Prof. Atztogo

I installed the Phono3py by "conda install -c atztogo phono3py". But for each Phono3py command, it always ends with the following error:
Traceback (most recent call last):
  File "/home/xiangp/anaconda3/envs/python368/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.17.0.post1', 'phono3py')
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/phono3py-1.17.0.post1-py3.6-linux-x86_64.egg-info/scripts/phono3py", line 477, in <module>
    filename="phono3py_disp.yaml")
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/phono3py-1.17.0.post1-py3.6-linux-x86_64.egg-info/scripts/phono3py", line 84, in finalize_phono3py
    ph3py_yaml.set_phonon_info(phono3py)
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/phono3py/cui/phono3py_yaml.py", line 81, in set_phonon_info
    super(Phono3pyYaml, self).set_phonon_info(phono3py)
  File "/home/xiangp/anaconda3/envs/python368/lib/python3.6/site-packages/phonopy/interface/phonopy_yaml.py", line 118, in set_phonon_info
    self.force_constants = phonopy.force_constants
AttributeError: 'Phono3py' object has no attribute 'force_constants'

By the way, I tested the case in Example and the results seem to be consistent.

Thank you very much!

Best,
Pan

**Comment by atztogo** [comment]
Could you try to use latest develop branches of phonopy and phono3py on github (https://github.com/atztogo/phonopy, https://github.com/atztogo/phono3py)?

**Comment by atztogo** [comment]
No.

**Comment by xiangpan2017** [comment]
I tried to install the latest develop branches of phonopy and phono3py. The phonopy-develop succeeded, but phono3py-develop did not with below error after executing the command "python setup.py install --user":
/home/xiangp/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
In file included from c/_lapackepy.c:39:0:
c/harmonic_h/lapack_wrapper.h:45:21: fatal error: lapacke.h: No such file or directory
 #include <lapacke.h>
                     ^
compilation terminated.
error: command 'gcc' failed with exit status 1

I know it may be a problem with setup.py, but I do not how to solve it. Do you have some suggests? Thank you!

**Comment by atztogo** [comment]
You may need to let the compiler know the header location,

export C_INCLUDE_PATH=$CONDA_PREFIX/include

On Mon, Oct 7, 2019 at 9:26 PM xiangpan2017 <notifications@github.com> wrote:
>
> I tried to install the latest develop branches of phonopy and phono3py. The phonopy-develop succeeded, but phono3py-develop did not with below error after executing the command "python setup.py install --user":
> /home/xiangp/miniconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
> #warning "Using deprecated NumPy API, disable it with "
> ^
> In file included from c/_lapackepy.c:39:0:
> c/harmonic_h/lapack_wrapper.h:45:21: fatal error: lapacke.h: No such file or directory
> #include <lapacke.h>
> ^
> compilation terminated.
> error: command 'gcc' failed with exit status 1
>
> I know it may be a problem with setup.py, but I do not how to solve it. Do you have some suggests? Thank you!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Atsushi Togo
Elements Strategy Initiative for Structural Materials, Kyoto university
E-mail: atz.togo@gmail.com

**Comment by xiangpan2017** [comment]
I loaded the following environment before compiling and then executed “python setup.py install --user” to compile:
Loading module for GNU compilers
GNU 6.4.0 is now loaded
Loading module for LAPACK
LAPACK 3.8.0 and GCC 6.4.0 are now loaded
Loading module for GNU compilers
GNU 6.4.0 is now loaded
Loading module for OpenBLAS
OpenBLAS 0.2.20 and GCC 6.4.0 are now loaded

It seems to be successful and the error mentioned at the beginning is also gone. However, a new error of "Phono3py C-routine is not compiled correctly" appears during creating fc2.hdf and fc3.hdf as shown as below:
(base) [xiangp@dbn503-35-r bakFile]$ phono3py --dim_fc2="5 5 1" --dim="5 5 1" -c POSCAR-unitcell
        _                      _____
  _ __ | |__   ___  _ __   ___|___ / _ __  _   _
 | '_ \| '_ \ / _ \| '_ \ / _ \ |_ \| '_ \| | | |
 | |_) | | | | (_) | | | | (_) |__) | |_) | |_| |
 | .__/|_| |_|\___/|_| |_|\___/____/| .__/ \__, |
 |_|                                |_|    |___/
                                          1.17.0

Python version 3.7.3
Spglib version 1.13.0
******************************************************
Option names with underscores are deprecated, by which
the underscores are replaced by dashes. Therefore
'--dim_fc2' has to be written as '--dim-fc2'.
******************************************************

----------------------------- General settings -----------------------------
Run mode: None
HDF5 data compression filter: gzip
Crystal structure was read from "POSCAR-unitcell".
Supercell (dim): [5 5 1]
Phonon supercell (dim-fc2): [5 5 1]
Spacegroup: Cmmm (65)
Use -v option to watch primitive cell, unit cell, and supercell structures.
----------------------------- Force constants ------------------------------
Imposing translational and index exchange symmetry to fc2: False
Imposing translational and index exchange symmetry to fc3: False
Imposing symmetry of index exchange to fc3 in reciprocal space: False
Displacement dataset for fc3 is read from disp_fc3.yaml.
Sets of supercell forces are read from FORCES_FC3.
Computing fc3[ 1, x, x ] using numpy.linalg.pinv with displacements:
    [ 0.0300  0.0000  0.0000]
    [-0.0300  0.0000  0.0000]
    [ 0.0000  0.0000  0.0300]
Expanding fc3
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Phono3py C-routine is not compiled correctly.
Writing fc3 to fc3.hdf5
Max drift of fc3: -0.048051 (yxx) -0.021816 (yyx) 0.000079 (yyy)
Displacement dataset is read from disp_fc2.yaml.
Sets of supercell forces are read from FORCES_FC2.
Writing fc2 to fc2.hdf5
Max drift of fc2: 0.000001 (zz) 0.000001 (zz)
*************** None of ph-ph interaction was calculated. ****************
                 _
   ___ _ __   __| |
  / _ \ '_ \ / _` |
 |  __/ | | | (_| |
  \___|_| |_|\__,_|

**Comment by atztogo** [comment]
Probably you have several equivalent libraries and load wrong one that required by phono3py, but for this, I can't help you. I recommend to install phonopy and phono3py with the libraries installed via conda as shown below. It is important to ensure that PYTHONPATH is not set in your shell environment because this can conflict with conda system.

```
conda create -n dev -c conda-forge python=3.7
conda activate dev
conda install -c conda-forge gcc_linux-64 gxx_linux-64 matplotlib pyyaml scipy liblapacke h5py openblas
conda install -c conda-forge hdf5=1.8.20
mkdir dev
cd dev
git clone https://github.com/atztogo/phonopy.git
git clone https://github.com/atztogo/phono3py.git
cd phonopy
git checkout develop
python setup.py build
pip install -e .
cd ../phono3py
git checkout develop
python setup.py build
pip install -e .
```

If this way doesn't work, I have no idea how to help you.

**Comment by atztogo** [comment]
It seems dependency of above packages has been changed and I found the above instruction steps don't work properly.  So I worked to find the problem and I updated the documentation of installation instruction and ``setup.py``, see http://atztogo.github.io/phono3py/install.html#installation-instruction-of-latest-development-version-of-phono3py. Please have a look at this information, and try this installation steps (you will probably need the latest ``setup.py``).

**Comment by xiangpan2017** [comment]
That is great! According to this instruction, I quickly completed the installation. Thank you very much for your help! By the way, for the invalid versions I had installed, how should I uninstall them. Thanks again!

**Comment by atztogo** [comment]
It depends. But you can run ``pip uninstall phonopy`` and ``pip uninstall phono3py`` several times. After running these, it is recommended to find installed phonopy and phono3py and just ``rm -r`` them. If you use conda env, it is fairly easy and save just by `conda remove -n <your_env> --all`.

**Comment by Dimplerani9463** [comment]
Hi @atztogo and @xiangpan2017,
I am facing the same issue "Phono3py C-routine is not compiled correctly." I reinstalled phono3py multiple times and got the same error every time.
I am not able to open the link that you shared before. could you please let me know how to proceed?

**Comment by atztogo** [comment]
The page was moved to
https://phonopy.github.io/phono3py/install.html#installation-instruction-of-latest-development-version-of-phono3py
