### ISSUE TITLE
ImportError: symmetrize_compact_force_constants

### ISSUE THREAD

**Issue by foxik0070** [atztogo/phono3py#6]
Hello,

We have a problem with compilation latest phono3py version. We see problem import symmetrize_compact_force_constants

```console
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.12.9.5', 'phono3py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 750, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1534, in run_script
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/lib/python2.7/site-packages/phono3py-1.12.9.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 49, in <module>
    
  File "build/bdist.linux-x86_64/egg/phono3py/phonon3/__init__.py", line 6, in <module>
ImportError: cannot import name symmetrize_compact_force_constants
Traceback (most recent call last):
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.12.9.5', 'phono3py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 750, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1534, in run_script
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/lib/python2.7/site-packages/phono3py-1.12.9.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 49, in <module>
    
  File "build/bdist.linux-x86_64/egg/phono3py/phonon3/__init__.py", line 6, in <module>
ImportError: cannot import name symmetrize_compact_force_constants
Traceback (most recent call last):
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/bin/phono3py", line 4, in <module>
    __import__('pkg_resources').run_script('phono3py==1.12.9.5', 'phono3py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 750, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1534, in run_script
  File "/apps/all/phono3py/1.12.9.5-Py-2.7/lib/python2.7/site-packages/phono3py-1.12.9.5-py2.7-linux-x86_64.egg/EGG-INFO/scripts/phono3py", line 49, in <module>
    
  File "build/bdist.linux-x86_64/egg/phono3py/phonon3/__init__.py", line 6, in <module>
ImportError: cannot import name symmetrize_compact_force_constants
```

Compile with
* OpenBLAS/0.2.9
* numpy/1.14.2
* h5py/2.7.1
* matplotlib/2.1.1
* PyYAML/3.12
* GCC/6.3.0
* Python/2.7

Any ideas?

**Comment by atztogo** [comment]
Have you updated phonopy (not phono3py) to the latest version?

**Comment by foxik0070** [comment]
We have phonopy/1.12.4.11

**Comment by atztogo** [comment]
You need the latest one.

**Comment by foxik0070** [comment]
Hello, now work it!!! Thanks...

**Comment by atztogo** [comment]
Sorry that I am not careful about managing version dependency. Now I made a release of phonopy-1.12.8 and wrote this version number in requirements.txt in phono3py.
